### ISSUE TITLE
NPE: UserInfoFragment

### ISSUE THREAD

**Issue by bxute** [hapramp/1Rramp-Android#243]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
       at com.hapramp.ui.fragments.UserInfoFragment.setFollowingCount(UserInfoFragment.java:558)
       at com.hapramp.ui.fragments.UserInfoFragment.access$1800(UserInfoFragment.java:61)
```

**Comment by bxute** [comment]
Applied try-catch block
