### ISSUE TITLE
NPE: CompleteFollowingHelper

### ISSUE THREAD

**Issue by bxute** [hapramp/1Rramp-Android#245]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.remove(ArrayList.java:403)
       at com.hapramp.utils.CompleteFollowingHelper.onFollowingsAvailable(CompleteFollowingHelper.java:40)
```

**Comment by bxute** [comment]
Applied check on list size before removing item from it.
